### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by TomasthehearseXD** [kikikkiikk/Hydro-Acrylic#1]
请在readme里提示用户需要把仓库根目录放在一个单独的文件夹里（复制到addons里面后在addons里面看到了readme.md就搞笑了），因为插件不可嵌套摆放，有些人会直接把仓库根目录放在addons里（把addons当做仓库的根目录了？）
以zip文件打包下载仓库时，压缩包里自带的文件夹名称为Hydro-Acrylic-main，这可能导致readme内的指南不起作用（尤其会让钻牛角尖的用户暴怒），这里需要提示用户检查文件夹名称和文件目录再执行安装命令

**Comment by unDefFtr** [comment]
已添加安装插件后的文件目录树。
